### ISSUE TITLE
Unification of plan variables using .add_plan

### ISSUE THREAD

**Issue by igorcadelima** [jacamo-lang/jacamo#12] opened 2017-08-11 05:50 UTC
Hello,

I've come across what I believe to be a bug in Jason but I'm posting the issue here as I was also using CArtAgO when the bug appeared. 

Here is my simplified scenario:
I'm using an artefact which returns new plans by means of an operation. The agent which invokes such operation, should add the plans using the `.add_plan` IA. However, if any of the plans happen to have variables with the same name as another which is already being used by the agent, then the plans are added to the plan library with the variables already unified, which, I believe, should not happen.

[Here is a JaCaMo project](https://github.com/jacamo-lang/jacamo/files/1217016/add_plans.zip) which reproduces the problem. Basically, the agent code is the following:
```
!start.

+!start
  : .my_name(Name)
  <-
  .puts("My name is #{Name}");
  getPlans(Plans);
  .add_plan(Plans);
  
  .list_plans({ +!hello(_) });
  .list_plans({ +!bye(_) });
  
  !hello(bob);
  .print("----");
  !hello(alice).

{ include("$jacamoJar/templates/common-cartago.asl") }
```
The plans which are being added are the following:
```
+!hello(Name)
  : AnotherVar = 10
  <-
  .print(Name);
  .puts("Hello, #{Name}");
  .print("---");
  !bye(Name).
  
+!bye(Name)
  <-
  .print(AnotherVar);
  .puts("Bye, #{Name}").
```
The output is the following:

> [bob] My name is bob
> [bob] @l__11[source(self)] +!hello(bob) : (AnotherVar = 10) <- .print(bob); .puts("Hello, #{Name}"); !bye(bob).
> [bob] @l__12[source(self)] +!bye(bob) <- .print(AnotherVar); .puts("Bye, #{Name}").
> [bob] bob
> [bob] Hello, Name
> [bob] AnotherVar\<no-value\>
> [bob] Bye, Name
> [bob] ----
> [bob] No fail event was generated for +!hello(alice)[source(self)]
> [bob] 
> intention 2: 
>     +!start[source(self)] <- ... !hello(alice) / {Plans=[@l__11[source(self)] +!hello(Name) : (AnotherVar = 10) <- .print(Name); .puts("Hello, #{Name}"); !bye(Name).,@l__12[source(self)] +!bye(Name) <- .print(AnotherVar); .puts("Bye, #{Name}").], Name=bob}
> 
> [bob] Found a goal for which there is no applicable plan:+!hello(alice)[source(self)]

Is this really a bug? Thanks in advance.

**Comment by jomifred** [comment] 2017-08-11 13:11
Hi Igor, that is indeed the expected behavior -- vars are replaced before the add_plan execution (as the var Plans that have to be replaced). Someone can use this "feature" to change something in the plan before adding it.

Of course, we can discuss whether:
1. keep it as it is now (and add an internal action to pre-process your Plan variable properly before the add_plan) -- something like the makeVarAnnon method we have in java API
2. implement a kind of "one level unification" (to unify Plan but not the vars of the new value of Plans). I am just not sure it is a general solution
3. you produce your plan with vars that certainly will not accidentally clash with other var names :-) Again, in cases where .send askHow is used, we cannot avoid "bad" variable names.

**Comment by rbordini** [comment] 2017-08-11 13:35
an internal action ".rename_apart(X,Y)" sounds like a good idea!

**Comment by igorcadelima** [comment] 2017-08-11 14:43
Thanks for the reply! :)

Unfortunately, 3 is out of question. The artefact will actually be provided as a library and the additional plans could be obtained from anywhere (web, library's jar file, etc). As the agent file should created by other developers, I have no control over the variable names they use. I didn't mention this before because I wanted to simplify the problem (sorry about that!). 

I'm not sure if I understood 1 and 2 correctly, but it seems like 1 is more backwards compatible and 2 is what I was expecting to happen? If so, for the backwards compatibility, I'd also say that 1 is a better option.

**Comment by jomifred** [comment] 2017-08-11 15:53
So, let's go for 2. 

I committed this new internal action proposed by Rafael so that you can write your code as follows:

  getPlans(Plans);
  .rename_apart(Plans,RenPlans);
  .add_plan(RenPlans);

**Comment by igorcadelima** [comment] 2017-08-11 18:21
Thanks, @jomifred !

I'll let you know if any problem arises when I download the updated code and test the new IA.

I don't mean to be annoying, but wouldn't something like `.disunify`, `.disunify_vars`, or `.restore_vars` provide a clearer meaning of this new IA's purpose? It's not a big deal, though :)

**Comment by igorcadelima** [comment] 2017-08-11 19:11
I just tested it and it seems to work perfectly!

**Closed** 2017-08-11 19:12 UTC

**Comment by rbordini** [comment] 2017-08-11 19:27
the name of what you want to do, in the logic programming literature, is 
to "rename apart" the free variables. we will use the right name because 
there is no such thing as "disunify". :)

**Comment by igorcadelima** [comment] 2017-08-11 19:34
I didn't know this is a known term in the logic programming literature. Thanks for telling me that, @rbordini !

**Comment by igorcadelima** [comment] 2017-08-14 20:09
Hello again!

Could you please tell me why I'm getting outputs like 

> [bob] Hello, _26_25
> [bob] Bye, _27_25

instead of

> [bob] Hello, alice
> [bob] Bye, alice

when using `.puts` within renamed plans? 

For example, for the following plan
```
+!hello(Name)
  <-
  .concat("Hello, ", Name, M);
  .print(M);
  .puts("#{M}");
  !bye(Name).
```
the output is 

> [bob] Hello, alice
> [bob] _27_26

[Here is a project](https://github.com/jacamo-lang/jacamo/files/1223323/add_plans.zip) that reproduces this issue I just mentioned.

**Comment by jomifred** [comment] 2017-08-14 20:38
could you please check if you are using the latest github version of Jason?

the output for me is

	[bob] Hello, alice 
 	[bob] _27_26 
	[bob] alice

which suggest a bug in .put

> On 14 de ago de 2017, at 17:09, Igor C. A. de Lima <notifications@github.com> wrote:
> 
> Hello again!
> 
> Could you please tell me why I'm getting outputs like
> 
> [bob] Hello, _26_25
> [bob] Bye, _27_25
> 
> instead of
> 
> [bob] Hello, alice
> [bob] Bye, alice
> 
> when using .puts within renamed plans?
> 
> For example, for the following plan
> 
> +!hello(Name)
>   <-
>   .concat("Hello, ", Name, M);
>   .print(M);
>   .puts("#{M}");
>   !bye(Name).
> 
> the output is
> 
> [bob] Hello, alice
> [bob] _27_26
> 
> Here is a project that reproduces this issue I just mentioned.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by igorcadelima** [comment] 2017-08-14 20:46
I'm using the latest version from the master branch of Jason's repository.

**Comment by jomifred** [comment] 2017-08-14 21:03
I fixed the bug in .puts and committed in jason repository. Your example runs fine in my configuration and I hope it will run also in yours. 


> On 14 de ago de 2017, at 17:46, Igor C. A. de Lima <notifications@github.com> wrote:
> 
> I'm using the latest version from the master branch of Jason's repository.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by igorcadelima** [comment] 2017-08-16 00:20
I'm getting
```
[bob] Hello, alice
[bob] "Hello, alice"
[bob] alice
```
Are those quotes expected in the output? I can't remember whether they used to appear when there was nothing but an interpolation in the string passed as argument as in `.puts("#{M}")`. If so, the issue seems to be solved.

**Comment by jomifred** [comment] 2017-08-16 17:01
fixed.

> On 15 de ago de 2017, at 21:20, Igor C. A. de Lima <notifications@github.com> wrote:
> 
> I'm getting
> 
> [bob] Hello, alice
> [bob] "Hello, alice"
> [bob] alice
> 
> Are those quotes expected in the output? I can't remember whether they used to appear when there was nothing but an interpolation in the string passed as argument as in .puts("#{M}"). If so, the issue seems to be solved.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)
